version: "3.9"

services:
  usersmapapp-api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: Usersmapapp-API
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - 8000:8000
    env_file:
      - .env
    restart: "on-failure"
    depends_on:
      - postgres-db
    networks:
      - usersmapapp-api
    
  postgres-db:
    image: postgis/postgis:14-3.3
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    restart: 'on-failure'
    networks:
      - usersmapapp-api

networks:
  usersmapapp-api:
    driver: bridge

volumes:
  postgres_data:
